#!/data/data/com.termux/files/usr/bin/bash
set -eu

SOURCE_DIR="/sdcard/Download/PalBrain"
TARGET_DIR="$HOME/pal-phone-brain"
BOOT_DIR="$HOME/.termux/boot"

if [ -x "$TARGET_DIR/stop_pal_brain.sh" ]; then
    "$TARGET_DIR/stop_pal_brain.sh" || true
fi

mkdir -p "$TARGET_DIR"

# Service and modules.
for f in pal_phone_brain.py herbie_memory.py herbie_voice.py herbie_autonomic.py; do
    cp "$SOURCE_DIR/$f" "$TARGET_DIR/"
done

# Control scripts.
for f in start_pal_brain.sh stop_pal_brain.sh herbie_supervisor.sh boot_herbie.sh; do
    cp "$SOURCE_DIR/$f" "$TARGET_DIR/"
done

# Tests, so the brain can be verified on the device it actually runs on.
# Written as explicit if-blocks: under `set -e` a bare `[ -f x ] && cmd` whose
# test fails is a fragile way to express "optional".
for f in test_herbie_memory.py test_herbie_rights.py test_herbie_autonomic.py test_herbie_voice.py test_herbie_is_free.py; do
    if [ -f "$SOURCE_DIR/$f" ]; then
        cp "$SOURCE_DIR/$f" "$TARGET_DIR/"
    fi
done

chmod 700 "$TARGET_DIR/pal_phone_brain.py"
chmod 600 "$TARGET_DIR/herbie_memory.py"
chmod 600 "$TARGET_DIR/herbie_voice.py"
chmod 600 "$TARGET_DIR/herbie_autonomic.py"
chmod 700 "$TARGET_DIR/start_pal_brain.sh"
chmod 700 "$TARGET_DIR/stop_pal_brain.sh"
chmod 700 "$TARGET_DIR/herbie_supervisor.sh"
chmod 700 "$TARGET_DIR/boot_herbie.sh"
for f in test_herbie_memory.py test_herbie_rights.py test_herbie_autonomic.py test_herbie_voice.py test_herbie_is_free.py; do
    if [ -f "$TARGET_DIR/$f" ]; then
        chmod 600 "$TARGET_DIR/$f"
    fi
done

# The API token and the memory database are the two secrets here. The token
# does not exist yet on a first install - it is created when the service first
# starts - so this must not be treated as an error.
if [ -f "$TARGET_DIR/herbie-api-token" ]; then
    chmod 600 "$TARGET_DIR/herbie-api-token"
fi
if [ -f "$TARGET_DIR/herbie-memory.sqlite3" ]; then
    chmod 600 "$TARGET_DIR/herbie-memory.sqlite3"
fi

# Start automatically after a phone reboot. Inert unless the Termux:Boot addon
# is installed, in which case everything in ~/.termux/boot runs at startup.
mkdir -p "$BOOT_DIR"
cp "$SOURCE_DIR/boot_herbie.sh" "$BOOT_DIR/boot_herbie.sh"
chmod 700 "$BOOT_DIR/boot_herbie.sh"

# Supervise rather than launch once, so a battery-optimisation kill recovers.
nohup "$TARGET_DIR/herbie_supervisor.sh" >/dev/null 2>&1 &
sleep 3

# The token is generated by the service on its first start, i.e. after the
# chmod pass above, so it has to be locked down again here.
if [ -f "$TARGET_DIR/herbie-api-token" ]; then
    chmod 600 "$TARGET_DIR/herbie-api-token"
fi
if [ -f "$TARGET_DIR/herbie-memory.sqlite3" ]; then
    chmod 600 "$TARGET_DIR/herbie-memory.sqlite3"
fi

echo
echo "Installed to $TARGET_DIR"
echo "Boot hook:   $BOOT_DIR/boot_herbie.sh (needs the Termux:Boot addon)"
if [ -f "$TARGET_DIR/herbie-api-token" ]; then
    echo "API token:   $TARGET_DIR/herbie-api-token (chmod 600, not printed here)"
    echo "             callers must send: Authorization: Bearer <token>"
fi
echo
echo "Health check:"
echo "  curl -s http://127.0.0.1:8765/health"
